cameras:
  vars:
      ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    overhead-camera:
     ansible_host: camera-pi-a.local
     input_raspicam_args: '-x 1060 -y 596 -rot 90 -fps 30 -quality 100 -stats'
     raspistill_args: '--nopreview -rot 90'
    fisheye-camera:
      ansible_host: camera-pi-b.local
      input_raspicam_args: '-x 450 -y 500 -fps 15 -quality 25'
      raspistill_args: "--nopreview"
    microscope-camera:
      ansible_host: camera-pi-c.local
      input_raspicam_args: "-x 860 -y 1080 -preview -br 50 -rot 270 --awb off -awbgainR 3.9 -awbgainB 1.40' -quality 100"
      raspistill_args: "--nopreview --flicker 60hz --brightness 50 -rot 270 --awb off -awbg '3.9,1.40'"
