---
- name: Start Streaming
  hosts: cameras
  user: pi
  become: true
  tasks:
    - name: start
      tags: start
      block:
        - name: Read installed packages
          package_facts:
            manager: apt
        - name: Read running services
          service_facts:
        - name: Make sure stream is stopped
          systemd:
            name: network_stream
            state: stopped
            enabled: yes
            daemon_reload: yes
          when: "'network_stream.service' in ansible_facts.services"
        - name: Install VLC
          apt:
            name: vlc
            state: present
          when: '"vlc" not in ansible_facts.packages'
        - name: Copy streaming script
          template:
            src: start_streaming.sh
            dest: /home/pi
            mode: +x
        - name: Copy systemd service file to server
          template:
            src: network_stream.service
            dest: /etc/systemd/system
            owner: root
            group: root
        - name: Start Streaming
          systemd:
            name: network_stream
            state: restarted
            enabled: no
            daemon_reload: yes
    - name: stop
      tags: stop
      block:
        - name: Stop Streaming
          systemd:
            name: network_stream
            state: stopped
            daemon_reload: yes
